### ISSUE TITLE
How to generate a video about the novel view？

### ISSUE THREAD

**Issue by dhgras** [InternLandMark/LandMark#10]
What I'm not so sure about is that right now the code can only generate videos using the test dataset, and this video is usually not continuous? How can I render to generate the novel view and continuous video? As shown in the demo video.

**Comment by kam1107** [comment]
Hi, to create a video, you need to create a trajectory either using a function like, e.g. https://github.com/yenchenlin/nerf-pytorch/blob/63a5a630c9abd62b0f21c08703d0ac2ea7d4b9dd/load_blender.py#L29, or draw it yourself. To do this, you can either extract a scene point cloud and import to Blender, draw a trajectory, then export the trajectory; or you can resort to nerfstudio: https://docs.nerf.studio/en/latest/quickstart/viewer_quickstart.html

**Comment by xiaowenhe** [comment]
> Hi, to create a video, you need to create a trajectory either using a function like, e.g. https://github.com/yenchenlin/nerf-pytorch/blob/63a5a630c9abd62b0f21c08703d0ac2ea7d4b9dd/load_blender.py#L29, or draw it yourself. To do this, you can either extract a scene point cloud and import to Blender, draw a trajectory, then export the trajectory; or you can resort to nerfstudio: https://docs.nerf.studio/en/latest/quickstart/viewer_quickstart.html

@kam1107 @dhgras  , Hi, can give a demo code for generate continuous video, I am a newer for this. Thank you!

**Comment by CyLcgj** [comment]
@xiaowenhe Hello, have you solved this problem? I'm experiencing the same issue now and would like to know how you addressed it. Thank you.

**Comment by PP-explore** [comment]
@kam1107 @eveneveno @Saaaaln @FrankYzy Excuse me, I would like to ask about how to extract the point cloud after the model is trained? The training doesn't seem to output relevant point cloud data
