### ISSUE TITLE
Once the model is trained and rendered, how do you view the results?

### ISSUE THREAD

**Issue by Blackkkk07** [InternLandMark/LandMark#14]
@kam1107 @zyfhaha @taomiao @eveneveno @Saaaaln  After rendering is complete, there are only four images and one txt file in the imgs_test_all folder

**Comment by Saaaaln** [comment]
Hi, to render all the images, you could use the following code
 `interval = 1 if self.N_vis < 0 else max(N // self.N_vis, 1)`
 `test_idx = list(range(0, N, interval))`
to replace [test_idx = list(range(0, N, self.N_vis))](https://github.com/InternLandMark/LandMark/blob/main/app/tools/dataloader/city_dataset.py#L45C7-L45C7).

And then, set `N_vis = -1` to rendering all images. Also, you could set `generate_videos = 1` to generate videos.

**Comment by Blackkkk07** [comment]
Ok, I'll try. Thank you for your answer
