### ISSUE TITLE
MatrixCity Dataset

### ISSUE THREAD

**Issue by EricLee0224** [InternLandMark/LandMark#23]
Hi,

Thank you for your wonderful work! Sorry that the dataset used by your gridnerf cannot be made public, I would like to ask if your latest dataset MatrixCity can be used for gridnerf? Could authors provide an official pipeline? thx!

**Comment by Saaaaln** [comment]
We have supported MatrixCity Dataset. Please pay attention to our latest commit.

**Comment by EricLee0224** [comment]
🐂！
