### ISSUE TITLE
请问,使用单GPU训练MatrixCity Dataset数据的时候，需要多少内存配置的服务器？我32G的服务器，进度条只能走到24%，然后程序就崩溃了

### ISSUE THREAD

**Issue by MIM1993** [InternLandMark/LandMark#28]

**Comment by Saaaaln** [comment]
Is 32G you mentioned the total size of the host memory? If so, it's obviously not enough. 

For the tiny settings in `app/confs/matrixcity/matrixcity_2block_lowquality.txt`, the host memory and GPU memory we recommend at least 500GB and 30GB respectively.

For your specific problem, you can post your error and your config here.

**Comment by MIM1993** [comment]
Your reply is very helpful to me. Thank you very much
