### ISSUE TITLE
How to set proper training bound

### ISSUE THREAD

**Issue by FlushingCat** [InternLandMark/LandMark#3]
Hi guys, I still haven't figured out how to set **--lb** and **--ub** specifically according to **poses pounds**. If **poses pounds** are as follows
![image](https://github.com/InternLandMark/LandMark/assets/42953352/3a60749f-cd25-42a0-a412-dab0f3f8f28e)
Is it reasonable for me to set 
lb = [22.02,7.50,-5140.63]
ub = [571.05,209.79,-203.64] ?

_Originally posted by @caohh019 in https://github.com/InternLandMark/LandMark/issues/1#issuecomment-1661425212_

**Comment by FlushingCat** [comment]
The key to setting `--ub` and `--lb` is to make them larger than the camera pose bounds, but not that large.
And the center of the scene box should be close to the center of the pose distribution.
In your case, my advice wil be: 

lb = [90, 20, -1050]
up =[130, 60 -1000]

FYI.

**Comment by caohh019** [comment]
Thank you for your reply. I'll try as you say.

**Comment by BaiBF** [comment]
> 
hi Can you tell me where to obtain this information about train poses and test poses? thanks

**Comment by FlushingCat** [comment]
You're welcome! The poses bounds will be printed out after the datasets successfully loaded.
