### ISSUE TITLE
About the value of --ndims

### ISSUE THREAD

**Issue by caohh019** [InternLandMark/LandMark#4]
When the value of **--ndims = 1**, the values of **matMode** and **vecMode** in GridNeRF are **[0, 2]** and **1** respectively, which means that the features in xy-plane and z-axis (line) are computed, and the xy-plane in this case corresponds to the ground in the scene, right? 
But if in my data, the plane where my ground is located is the xz plane, and the y-axis is perpendicular to the direction of the sky and the ground, how do I set the value of --ndims, or modify the code?

**Comment by caohh019** [comment]
That is to say I would like to know how to adjust the parameters or change the code when the ground is no longer represented by the xy plane in the data.

**Comment by zyfhaha** [comment]
For example, If u want to use xz plane, and the y-axis, u can move them to the first place like this:
`self.matMode = [[0, 2], [0, 1], [1, 2]][: self.ndims]`
`self.vecMode = [1, 2, 0][: self.ndims]`
