### ISSUE TITLE
ModuleNotFoundError: No module named 'app.tools'

### ISSUE THREAD

**Issue by ywaison** [InternLandMark/LandMark#41]
Hello, after I configured the data result according to your reademe, I ran the code python app/trainer.py --config confs/matrixcity/matrixcity_2block_multi.txt and an error appeared, and the error result was as follows
![IN{Z%K_3`M8%SS$0{P)HJMJ](https://github.com/InternLandMark/LandMark/assets/138007686/ad86f731-2fb5-40bf-a6db-65c94c9965e9)
Thanks again for sharing the code, I'd love to get a quick answer！

**Comment by jgghjgj** [comment]
I also encountered the same problem, have you solved it?

**Comment by jgghjgj** [comment]
@ywaison

**Comment by zhywanna** [comment]
same，solved? @jgghjgj @ywaison

**Comment by Yang067** [comment]
@zhywanna @jgghjgj @ywaison how to finish this question?
