### ISSUE TITLE
How to convert the contextcapture result to LandMark dataset format

### ISSUE THREAD

**Issue by chufall** [InternLandMark/LandMark#5]
Hi, this is an amazing work!

I have > 1000 images taken by a drone and reconstructed by ContextCapture as same as  what mentioned in your grid-nerf paper.
So how to convert the result of ContextCapture into the LandMark dataset format ?
Is there any code or pipeline to do it?
Thanks a lot!

chu

**Comment by kam1107** [comment]
Thanks for your interests! 
Please first export xml pose file (under ENU coordinate) from ContextCapture. 
Here's a reference code of converting the xml pose file to our pose format (.json): https://drive.google.com/file/d/1Hilc93M2G0rLatz093REilrT6Rub8a5c/view?usp=sharing
You may want to change the way to iterate through photos/photo groups based on your own xml file.

**Comment by chufall** [comment]
Thanks a lot !!! I will try!

**Comment by chufall** [comment]
@kam1107 
There're some bugs in your code, and I have fixed it. 
[https://drive.google.com/file/d/1tFvti9y1fv7XflVI2Fyt6NEsJQYx6FIV/view?usp=sharing](url)

Here's something need to be confirmed:
1. The result of the code is a json file named drone_3.json,  whose format is different with which need by CityDataset class (transforms_train.json and transforms_test.json) , should I convert it?

2. When  I used the tools/colmap2nerf.py to convert a colmap dataset, and  trained it , the CityDataset class will return a error "KeyError: 'focal'" in line 113 of app/tools/dataloader/ray_utils.py 
I found  there isn't the key "focal" in the  transforms_train.json  outputed by  colmap2nerf.py.


Thanks a lot!

**Comment by FlushingCat** [comment]
Hi! about the `"KeyError: 'focal'"` problem, this thread may help you
#1

**Comment by chufall** [comment]
@kam1107 @FlushingCat  I have successfully submited the traning job! 
Thanks a lot！

**Comment by chufall** [comment]
> > @kam1107 There're some bugs in your code, and I have fixed it. [https://drive.google.com/file/d/1tFvti9y1fv7XflVI2Fyt6NEsJQYx6FIV/view?usp=sharing](url)
> > Here's something need to be confirmed:
> > 
> > 1. The result of the code is a json file named drone_3.json,  whose format is different with which need by CityDataset class (transforms_train.json and transforms_test.json) , should I convert it?
> > 2. When  I used the tools/colmap2nerf.py to convert a colmap dataset, and  trained it , the CityDataset class will return a error "KeyError: 'focal'" in line 113 of app/tools/dataloader/ray_utils.py
> >    I found  there isn't the key "focal" in the  transforms_train.json  outputed by  colmap2nerf.py.
> > 
> > Thanks a lot!
> 
> @chufall Do you solve this problem?`json format is different with which need by CityDataset class (transforms_train.json and transforms_test.json)"` please help me out!!!

[drone2nerf.zip](https://github.com/InternLandMark/LandMark/files/14681115/drone2nerf.zip)

Hi, sorry for later!
Try my code, and the command line is the following
--drone_xml xxx\blockexchange.xml --output_dir xxxx\output
