### ISSUE TITLE
CUDA out of memeory

### ISSUE THREAD

**Issue by ghd98522** [InternLandMark/LandMark#9]
Why did I only account for 10G when I first started training, when I trained to 4%, the cuda memory accounted for 20G, and when I was 6%, CUDA out of memory. I used the 3090
![1691490024193](https://github.com/InternLandMark/LandMark/assets/141723481/ebafd9f6-c51e-4e74-9d2e-58558a616dcb)

**Comment by FlushingCat** [comment]
Hi！The training process consumes memory a lot. For reference, training with a dataset contains about 250 imgs and the city_tiny config needs about 23488 MB of memory. Using an A100 GPU if possible, or  any GPU with memory larger than ~24GiB

**Comment by zyfhaha** [comment]
You can also try to lower the "N_voxel_final" in config, if you still want to use 3090, but the result will be worse.
